# Generated by Django 2.1.5 on 2019-02-21 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restReview', '0002_auto_20190221_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular course across whole system.', primary_key=True, serialize=False),
        ),
    ]
